version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/GitHubActions/GitHubActions.csproj" # Location of package manifests
    schedule:
      interval: "daily"
