# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
name: "Dependabot"
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/GitHubActions/GitHubActions.csproj" # Location of package manifests
    schedule:
      interval: "daily"
