version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "GitHubActions/GitHubActions.csproj"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
