name: GitHub Actions Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
   - cron: '30 14 * * *'
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.404
    - name: Restaurar Dependencias
      run: dotnet restore
    - name: Compilar
      run: dotnet build --no-restore
    - name: Testar
      run: dotnet test --no-build --verbosity normal
