name: GitHub Actions Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:    

jobs:

  build:
  
    env:
      MY_CUSTOM_MESSAGE: This is my first env variable

    runs-on: ubuntu-latest

    steps:
    
    - name: Exibir uma variável de ambiente
      run: echo ${{ ENV.MY_CUSTOM_MESSAGE }}
    
    - name: Exibir Nome do Repositório
      run: echo $GITHUB_REPOSITORY
    
    - name: Teste com PowerShell
      shell: pwsh
      run: |
        Write-Host "Usando PowerShell"
        
    - name: Listar Versões do .NET SDK
      run: dotnet --list-sdks
      
    - name: Exibir Secret
      run: echo O valor é ${{ secrets.MY_SECRET_SECRETO }}. O secret não é exibido no log por questões de segurança 
    
    - name: Repository Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET    
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.404
        
    - name: Restaurar Dependencias
      #using power shell instead of bash
      shell: pwsh
      run: dotnet restore
      
    - name: Compilar
      run: dotnet build --no-restore
      
    - name: Testar
      run: dotnet test --no-build --verbosity normal
      
    # - name: Simular Step com Falha
    #   run: exit 1
      
    - name: Enviar Notificação de falha
      if: failure()
      run: echo Notificando Falha de Workflow
      
  push:
  
    runs-on: ubuntu-latest
    
    needs: [build]
      
    steps:
    
     - uses: actions/checkout@v2
       
     - name: Docker Login
       uses: docker/login-action@v2.1.0
       with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}       
        
     - name: Build and push
       uses: docker/build-push-action@v5
       with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/githubactions:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
  deploy:
  
    runs-on: ubuntu-latest
    
    needs: [push]    

    steps:
      
      - name: Azure Login
        uses: Azure/login@v1.4.5
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2.2.10
        with:
          app-name: my-movies-and-series
          images: ${{secrets.DOCKER_USERNAME}}/githubactions:latest 
