name: GitHub Actions Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
   - cron: '35 17 * * *'
    

jobs:
  build:
  
    env:
      NOME_IMAGEM: githubactions
      NOME_COMPLETO_IMAGEM: ${{ secrets.DOCKER_USERNAME }}/$NOME_IMAGEM

    runs-on: ubuntu-latest

    steps:
    
    - name: Exibir Nome do Repositório
      run: echo $GITHUB_REPOSITORY
    
    - name: Teste com PowerShell
      shell: pwsh
      run: |
        Write-Host "Usando PowerShell"
        
    - name: Listar Versões do .NET SDK
      run: dotnet --list-sdks
      
    - name: Exibir Secret
      run: echo O valor é ${{ secrets.MY_SECRET_SECRETO }}. O secret não é exibido no log por questões de segurança 
    
    - uses: actions/checkout@v3
    - name: Setup .NET
    
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.404
        
    - name: Restaurar Dependencias
      #using power shell instead of bash
      shell: pwsh
      run: dotnet restore
      
    - name: Compilar
      run: dotnet build --no-restore
      
    - name: Testar
      run: dotnet test --no-build --verbosity normal
      
    # - name: Simular Step com Falha
    #   run: exit 1
      
    - name: Enviar Notificação de falha
      if: failure()
      run: echo Notificando Falha de Workflow
      
  push:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    
     - name: Exibir Nome do Repositório
       run: echo ${{env.NOME_COMPLETO_IMAGEM}}:$GITHUB_RUN_NUMBER
       
     - name: Docker Login
       uses: docker/login-action@v2.1.0
       with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}     
        
     - name: Build and push
       uses: docker/build-push-action@v3
       with:
        context: .
        push: true
        tags: ${{env.NOME_COMPLETO_IMAGEM}}:$GITHUB_RUN_NUMBER
